
CREATE TABLESPACE TBS_STAGE
    LOGGING
    DATAFILE '/u01/app/oracle/oradata/ORCL/ORCLPDB/TBS_STAGE.dbf'
    SIZE 1M
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER starea IDENTIFIED BY starea0123
    DEFAULT TABLESPACE TBS_STAGE
    TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE TO starea;
GRANT UNLIMITED TABLESPACE TO starea;


GRANT SELECT ON source.TB_CADASTRO_CLIENTE TO starea;
GRANT SELECT ON source.TB_ENDERECO         TO starea;
GRANT SELECT ON source.TB_PRODUTO          TO starea;
GRANT SELECT ON source.TB_CATEGORIA        TO starea;
GRANT SELECT ON source.TB_LOCALIDADE       TO starea;
GRANT SELECT ON source.TB_PEDIDOS          TO starea;
GRANT SELECT ON source.TB_ITENS_PEDIDO     TO starea;


CREATE TABLE ST_CADASTRO_CLIENTE (
    ID_CLIENTE    INTEGER      NOT NULL,
    NOME_CLIENTE  VARCHAR2(50),
    EMAIL_CLIENTE VARCHAR2(100)
);

CREATE TABLE ST_ENDERECO (
    ID_ENDERECO INTEGER     NOT NULL,
    LOGRADOURO  VARCHAR2(100),
    NUMERO      VARCHAR2(10),
    CIDADE      VARCHAR2(50),
    ESTADO      VARCHAR2(2),
    PAIS        VARCHAR2(30),
    CEP         VARCHAR2(10),
    ID_CLIENTE  INTEGER
);

CREATE TABLE ST_PRODUTO (
    ID_PRODUTO   INTEGER      NOT NULL,
    SKU          VARCHAR2(30),
    NOME_PRODUTO VARCHAR2(100),
    ID_CATEGORIA INTEGER
);

CREATE TABLE ST_CATEGORIA (
    ID_CATEGORIA       INTEGER      NOT NULL,
    NOME_CATEGORIA     VARCHAR2(20),
    NOME_SUB_CATEGORIA VARCHAR2(20)
);

CREATE TABLE ST_LOCALIDADE (
    ID_LOCALIDADE     INTEGER      NOT NULL,
    NOME_LOCALIDADE   VARCHAR2(100),
    CIDADE_LOCALIDADE VARCHAR2(20)
);

CREATE TABLE ST_PEDIDOS (
    ID_TRANSACAO     INTEGER      NOT NULL,
    DATA_TRANSACAO   TIMESTAMP,
    DATA_ENTREGA     TIMESTAMP,
    STATUS_PAGAMENTO VARCHAR2(20),
    ID_CLIENTE       INTEGER,
    ID_LOCALIDADE    INTEGER
);

CREATE TABLE ST_ITENS_PEDIDO (
    ID_TRANSACAO   INTEGER          NOT NULL,
    ID_PRODUTO     INTEGER          NOT NULL,
    QUANTIDADE     INTEGER,
    PRECO_UNITARIO DOUBLE PRECISION
);


TRUNCATE TABLE ST_CADASTRO_CLIENTE;
INSERT INTO ST_CADASTRO_CLIENTE SELECT * FROM source.TB_CADASTRO_CLIENTE;
COMMIT;

TRUNCATE TABLE ST_ENDERECO;
INSERT INTO ST_ENDERECO SELECT * FROM source.TB_ENDERECO;
COMMIT;

TRUNCATE TABLE ST_PRODUTO;
INSERT INTO ST_PRODUTO SELECT * FROM source.TB_PRODUTO;
COMMIT;

TRUNCATE TABLE ST_CATEGORIA;
INSERT INTO ST_CATEGORIA SELECT * FROM source.TB_CATEGORIA;
COMMIT;

TRUNCATE TABLE ST_LOCALIDADE;
INSERT INTO ST_LOCALIDADE SELECT * FROM source.TB_LOCALIDADE;
COMMIT;

TRUNCATE TABLE ST_PEDIDOS;
INSERT INTO ST_PEDIDOS SELECT * FROM source.TB_PEDIDOS;
COMMIT;

TRUNCATE TABLE ST_ITENS_PEDIDO;
INSERT INTO ST_ITENS_PEDIDO SELECT * FROM source.TB_ITENS_PEDIDO;
COMMIT;
