


SELECT * FROM ST_CADASTRO_CLIENTE;


ALTER TABLE ST_CADASTRO_CLIENTE ADD (DATA_REGISTRO DATE);

UPDATE ST_CADASTRO_CLIENTE SET DATA_REGISTRO = CURRENT_DATE;
COMMIT;


UPDATE ST_CADASTRO_CLIENTE
SET EMAIL_CLIENTE = 'nao informado'
WHERE EMAIL_CLIENTE IS NULL;
COMMIT;


UPDATE ST_CADASTRO_CLIENTE
SET EMAIL_CLIENTE = 'nao informado'
WHERE SUBSTR(EMAIL_CLIENTE, 1, 3) = 'xxx';
COMMIT;


CREATE OR REPLACE FUNCTION isNumeric(p_str VARCHAR2)
RETURN NUMBER
IS
    l_num NUMBER;
BEGIN
    l_num := TO_NUMBER(p_str);
    RETURN 1;
EXCEPTION
    WHEN VALUE_ERROR THEN
        RETURN 0;
END isNumeric;
/


UPDATE ST_CADASTRO_CLIENTE
SET EMAIL_CLIENTE = 'nao informado'
WHERE isNumeric(EMAIL_CLIENTE) = 1;
COMMIT;


CREATE TABLE ST_DIM_CLIENTE (
    NK_ID_CLIENTE       VARCHAR2(20),
    NM_CLIENTE          VARCHAR2(50),
    NM_CIDADE_CLIENTE   VARCHAR2(50),
    FLAG_ACEITA_CAMPANHA CHAR(1),
    DESC_CEP            VARCHAR2(10)
);


INSERT INTO ST_DIM_CLIENTE
SELECT
    A.ID_CLIENTE,
    A.NOME_CLIENTE,
    B.CIDADE,
    0,       -- FLAG_ACEITA_CAMPANHA: padrão = não aceita
    B.CEP
FROM ST_CADASTRO_CLIENTE A
JOIN ST_ENDERECO B ON A.ID_CLIENTE = B.ID_CLIENTE;
COMMIT;


SELECT * FROM ST_DIM_CLIENTE;
