
SELECT * FROM ST_LOCALIDADE;


CREATE TABLE ST_DIM_LOCALIDADE (
    NK_ID_LOCALIDADE    VARCHAR2(20) NOT NULL,
    NM_LOCALIDADE       VARCHAR2(50) NOT NULL,
    NM_CIDADE_LOCALIDADE VARCHAR2(50) NOT NULL,
    NM_REGIAO_LOCALIDADE VARCHAR2(50) NOT NULL
);


INSERT INTO ST_DIM_LOCALIDADE
SELECT
    ID_LOCALIDADE,
    NOME_LOCALIDADE,
    CIDADE_LOCALIDADE,
    CASE
        WHEN CIDADE_LOCALIDADE = 'Barueri'        THEN 'Sudeste'
        WHEN CIDADE_LOCALIDADE = 'São Paulo'       THEN 'Sudeste'
        WHEN CIDADE_LOCALIDADE = 'Rio de Janeiro'  THEN 'Sudeste'
        WHEN CIDADE_LOCALIDADE = 'Tatuapé'         THEN 'Sudeste'
        WHEN CIDADE_LOCALIDADE = 'Salvador'        THEN 'Nordeste'
        ELSE 'Outra região'
    END AS NM_REGIAO_LOCALIDADE
FROM ST_LOCALIDADE;
COMMIT;


SELECT * FROM ST_DIM_LOCALIDADE;
