
SELECT * FROM ST_PEDIDOS;
SELECT * FROM ST_ITENS_PEDIDO;

CREATE TABLE ST_VENDAS (
    ID_TRANSACAO     INTEGER,
    ID_CLIENTE       INTEGER,
    STATUS_PAGAMENTO VARCHAR2(28),
    ID_LOCALIDADE    INTEGER,
    DATA_VENDA       DATE,
    ID_PRODUTO       INTEGER,
    QUANTIDADE       INTEGER,
    PRECO_UNITARIO   DECIMAL
);


INSERT INTO ST_VENDAS (
    ID_TRANSACAO,
    ID_CLIENTE,
    STATUS_PAGAMENTO,
    ID_LOCALIDADE,
    DATA_VENDA,
    ID_PRODUTO,
    QUANTIDADE,
    PRECO_UNITARIO
)
SELECT
    P.ID_TRANSACAO,
    P.ID_CLIENTE,
    CASE
        WHEN P.STATUS_PAGAMENTO = 'NA' THEN 'Erro'
        ELSE P.STATUS_PAGAMENTO
    END AS STATUS_PAGAMENTO,
    P.ID_LOCALIDADE,
    P.DATA_ENTREGA,
    I.ID_PRODUTO,
    I.QUANTIDADE,
    I.PRECO_UNITARIO
FROM ST_PEDIDOS P
LEFT JOIN ST_ITENS_PEDIDO I
    ON P.ID_TRANSACAO = I.ID_TRANSACAO;
COMMIT;


SELECT * FROM ST_VENDAS;
