
CREATE TABLESPACE TBS_DW
    LOGGING
    DATAFILE '/u01/app/oracle/oradata/orcl/TBS_DW.dbf'
    SIZE 1M
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;


CREATE USER dw IDENTIFIED BY dw0123
    DEFAULT TABLESPACE TBS_DW;

GRANT CONNECT, RESOURCE TO dw;
GRANT UNLIMITED TABLESPACE TO dw;


GRANT SELECT ON starea.ST_DIM_CLIENTE    TO dw;
GRANT SELECT ON starea.ST_DIM_PRODUTO    TO dw;
GRANT SELECT ON starea.ST_DIM_LOCALIDADE TO dw;
GRANT SELECT ON starea.ST_VENDAS         TO dw;


CREATE SEQUENCE dim_cliente_id_seq
    START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TB_DIM_CLIENTE (
    SK_CLIENTE           INTEGER DEFAULT dim_cliente_id_seq.NEXTVAL,
    NK_ID_CLIENTE        VARCHAR2(20),
    NM_CLIENTE           VARCHAR2(50),
    NM_CIDADE_CLIENTE    VARCHAR2(50),
    FLAG_ACEITA_CAMPANHA CHAR(1),
    DESC_CEP             VARCHAR2(10),
    CONSTRAINT TB_DIM_CLIENTE_PK PRIMARY KEY (SK_CLIENTE) ENABLE
);


CREATE SEQUENCE dim_produto_id_seq
    START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TB_DIM_PRODUTO (
    SK_PRODUTO           INTEGER DEFAULT dim_produto_id_seq.NEXTVAL,
    NK_ID_PRODUTO        VARCHAR2(20) NOT NULL,
    DESC_SKU             VARCHAR2(50) NOT NULL,
    NM_PRODUTO           VARCHAR2(50) NOT NULL,
    NM_CATEGORIA_PRODUTO VARCHAR2(30) NOT NULL,
    NM_MARCA_PRODUTO     VARCHAR2(30) NOT NULL,
    CONSTRAINT TB_DIM_PRODUTO_PK PRIMARY KEY (SK_PRODUTO) ENABLE
);


CREATE SEQUENCE dim_localidade_id_seq
    START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TB_DIM_LOCALIDADE (
    SK_LOCALIDADE        INTEGER DEFAULT dim_localidade_id_seq.NEXTVAL,
    NK_ID_LOCALIDADE     VARCHAR2(20) NOT NULL,
    NM_LOCALIDADE        VARCHAR2(50) NOT NULL,
    NM_CIDADE_LOCALIDADE VARCHAR2(50) NOT NULL,
    NM_REGIAO_LOCALIDADE VARCHAR2(50) NOT NULL,
    CONSTRAINT TB_DIM_LOCALIDADE_PK PRIMARY KEY (SK_LOCALIDADE) ENABLE
);


CREATE TABLE TB_DIM_TEMPO (
    SK_DATA  INTEGER       NOT NULL,
    DATA     DATE          NOT NULL,
    NR_ANO   NUMBER(4)     NOT NULL,
    NR_MES   NUMBER        NOT NULL,
    NM_MES   VARCHAR2(20)  NOT NULL,
    NR_DIA   NUMBER        NOT NULL,
    CONSTRAINT TB_DIM_DATA_PK PRIMARY KEY (SK_DATA) ENABLE
);


CREATE TABLE TB_FATO_VENDA (
    SK_CLIENTE    INTEGER        NOT NULL,
    SK_PRODUTO    INTEGER        NOT NULL,
    SK_LOCALIDADE INTEGER        NOT NULL,
    SK_DATA       INTEGER        NOT NULL,
    VL_VENDA      DECIMAL(12, 4),
    QTD_VENDA     INTEGER,
    CONSTRAINT TB_FATO_VENDA_PK PRIMARY KEY (SK_CLIENTE, SK_PRODUTO, SK_LOCALIDADE, SK_DATA) ENABLE
);


INSERT INTO TB_DIM_TEMPO
SELECT
    TO_CHAR(TO_DATE('31/12/2012', 'DD/MM/YYYY') + NUMTODSINTERVAL(n, 'day'), 'YYYYMMDD') AS SK_DATA,
    TO_DATE('31/12/2012', 'DD/MM/YYYY') + NUMTODSINTERVAL(n, 'day')                      AS DATA,
    TO_CHAR(TO_DATE('31/12/2012', 'DD/MM/YYYY') + NUMTODSINTERVAL(n, 'day'), 'YYYY')     AS NR_ANO,
    TO_CHAR(TO_DATE('31/12/2012', 'DD/MM/YYYY') + NUMTODSINTERVAL(n, 'day'), 'MM')       AS NR_MES,
    TO_CHAR(TO_DATE('31/12/2012', 'DD/MM/YYYY') + NUMTODSINTERVAL(n, 'day'), 'Month')    AS NM_MES,
    TO_CHAR(TO_DATE('31/12/2012', 'DD/MM/YYYY') + NUMTODSINTERVAL(n, 'day'), 'DD')       AS NR_DIA
FROM (
    SELECT LEVEL n
    FROM dual
    CONNECT BY LEVEL <= 2000
);
COMMIT;
