
INSERT INTO TB_DIM_CLIENTE
SELECT
    dim_cliente_id_seq.NEXTVAL,
    NK_ID_CLIENTE,
    NM_CLIENTE,
    NM_CIDADE_CLIENTE,
    FLAG_ACEITA_CAMPANHA,
    DESC_CEP
FROM STAREA.ST_DIM_CLIENTE;
COMMIT;


SELECT * FROM TB_DIM_CLIENTE;


INSERT INTO TB_DIM_PRODUTO
SELECT
    dim_produto_id_seq.NEXTVAL,
    NK_ID_PRODUTO,
    DESC_SKU,
    NM_PRODUTO,
    NM_CATEGORIA_PRODUTO,
    NM_MARCA_PRODUTO
FROM STAREA.ST_DIM_PRODUTO;
COMMIT;

INSERT INTO TB_DIM_LOCALIDADE
SELECT
    dim_localidade_id_seq.NEXTVAL,
    NK_ID_LOCALIDADE,
    NM_LOCALIDADE,
    NM_CIDADE_LOCALIDADE,
    NM_REGIAO_LOCALIDADE
FROM STAREA.ST_DIM_LOCALIDADE;
COMMIT;


INSERT INTO TB_DIM_CLIENTE VALUES(-1, -1, '<não identificado>', '<não identificado>', 0, 'NA');
COMMIT;

INSERT INTO TB_DIM_PRODUTO VALUES(-1, -1, '<não identificado>', '<não identificado>', '<não identificado>', '<não identificado>');
COMMIT;

INSERT INTO TB_DIM_LOCALIDADE VALUES(-1, -1, '<não identificado>', '<não identificado>', '<não identificado>');
COMMIT;


INSERT INTO TB_FATO_VENDA
SELECT
    COALESCE(B.SK_CLIENTE,    -1) AS SK_CLIENTE,
    COALESCE(C.SK_PRODUTO,    -1) AS SK_PRODUTO,
    COALESCE(D.SK_LOCALIDADE, -1) AS SK_LOCALIDADE,
    TO_NUMBER(TO_CHAR(A.DATA_VENDA, 'yyyymmdd'), '99999999') AS SK_DATA,
    (A.PRECO_UNITARIO * A.QUANTIDADE) AS VL_VENDA,
    A.QUANTIDADE AS QTD_VENDA,
    CURRENT_DATE
FROM STAREA.ST_VENDAS A
LEFT JOIN TB_DIM_CLIENTE    B ON A.ID_CLIENTE    = B.NK_ID_CLIENTE
LEFT JOIN TB_DIM_PRODUTO    C ON A.ID_PRODUTO    = C.NK_ID_PRODUTO
LEFT JOIN TB_DIM_LOCALIDADE D ON A.ID_LOCALIDADE = D.NK_ID_LOCALIDADE;
COMMIT;


SELECT * FROM TB_FATO_VENDA;




ALTER TABLE TB_FATO_VENDA
    ADD CONSTRAINT TB_FATO_VENDA_FK_CLIENTE FOREIGN KEY (SK_CLIENTE)
    REFERENCES TB_DIM_CLIENTE (SK_CLIENTE) ENABLE;


ALTER TABLE TB_FATO_VENDA
    ADD CONSTRAINT TB_FATO_VENDA_FK_DATA FOREIGN KEY (SK_DATA)
    REFERENCES TB_DIM_TEMPO (SK_DATA) ENABLE;


ALTER TABLE TB_FATO_VENDA
    ADD CONSTRAINT TB_FATO_VENDA_FK_LOC FOREIGN KEY (SK_LOCALIDADE)
    REFERENCES TB_DIM_LOCALIDADE (SK_LOCALIDADE) ENABLE;


ALTER TABLE TB_FATO_VENDA
    ADD CONSTRAINT TB_FATO_VENDA_FK_PRO FOREIGN KEY (SK_PRODUTO)
    REFERENCES TB_DIM_PRODUTO (SK_PRODUTO) ENABLE;
